title: Asetukset
icon: mdi:tune
background: var(--background-image)
# The cards to show on this view.
cards:
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        title: Kodin tila-asetukset
        entities:
          - input_select.home_mode
          - input_boolean.guests
          - input_number.default_notification_volume_sonos
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        title: Automaatiot
        entities:
          - automation.lampotilailmoitus
          - automation.etuoven_valvonta_ovi_auki
  - type: entities
    show_header_toggle: false
    title: Muut tilat
    entities:
      - sensor.pesuhuoneen_lampotila
      - sensor.toilet_sensor_light_level
      - sensor.eteisen_liiketunnistin_light_level
      - sensor.vaatehuoneen_lampotila
      - sensor.vaatehuoneen_kosteus
  - type: vertical-stack
    title: "Muu valaistus"
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - input_boolean.hallway_light_automations
          - input_boolean.toilet_light_automations
          - input_boolean.cloakroom_light_automations
          - type: custom:slider-entity-row
            entity: light.eteisen_yleisvalot
            toggle: true
          - type: custom:slider-entity-row
            entity: light.kodin_tila
            toggle: true
          - type: custom:slider-entity-row
            entity: light.pesuhuone
            toggle: true
          - type: custom:slider-entity-row
            entity: light.vaatehuone
            toggle: true