homeassistant:

  packages: !include_dir_named packages

#############################
# COMPONENTS WITHOUT CONFIG #
#############################

default_config:
cloud:
conversation:
history:
logbook:
sun:
system_health:
device_tracker:
config:
http:
mobile_app:
person:
ffmpeg:
media_source:
energy:

###################################
# COMPONENTS WITH EXTERNAL CONFIG #
###################################

mqtt: !include config/mqtt.yaml
binary_sensor: !include config/binary_sensor.yaml
sensor: !include config/sensor.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
notify: !include config/notify.yaml
alarm_control_panel: !include config/alarm_control_panel.yaml
calendar: !include config/calendar.yaml
prometheus: !include config/prometheus.yaml
plant: !include config/plant.yaml
automation ui: !include automations.yaml
script: !include scripts.yaml
