homeassistant:

#############################
# COMPONENTS WITHOUT CONFIG #
#############################

default_config:
cloud:
conversation:
history:
logbook:
sun:
system_health:
device_tracker:
config:
http:
mobile_app:
person:
ffmpeg:
media_source:
energy:

###################################
# COMPONENTS WITH EXTERNAL CONFIG #
###################################

zone: !include config/zone.yaml
mqtt: !include config/mqtt.yaml
remote: !include config/remote.yaml
binary_sensor: !include config/binary_sensor.yaml
sensor: !include config/sensor.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
notify: !include config/notify.yaml
alarm_control_panel: !include config/alarm_control_panel.yaml
calendar: !include config/calendar.yaml
prometheus: !include config/prometheus.yaml
switch: !include config/switch.yaml
utility_meter: !include config/utility_meter.yaml
group: !include_dir_merge_named groups/
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts/
