homeassistant:
##############################
# COMPONENTS CONFIGURED HERE #
##############################

# lovelace: DEPRECATED
#   mode: yaml
#   resources:
#     - url: /local/button-card.js
#       type: module
#     - url: /local/plan-coordinates.js
#       type: module
#     - url: /local/battery-state-card.js
#       type: module
#     - url: /local/slider-entity-row.js
#       type: module

#############################
# COMPONENTS WITHOUT CONFIG #
#############################

cloud:
conversation:
history:
logbook:
map:
sun:
system_health:
device_tracker:
config:
http:
mobile_app:
python_script:
person:
ffmpeg:
media_source:
energy:

###################################
# COMPONENTS WITH EXTERNAL CONFIG #
###################################

discovery: !include config/discovery.yaml
zone: !include config/zone.yaml
mqtt: !include config/mqtt.yaml
recorder: !include config/recorder.yaml
remote: !include config/remote.yaml
binary_sensor: !include config/binary_sensor.yaml
sensor: !include config/sensor.yaml
input_boolean: !include config/input_boolean.yaml
input_number: !include config/input_number.yaml
input_select: !include config/input_select.yaml
timer: !include config/timer.yaml
notify: !include config/notify.yaml
panel_iframe: !include config/panel_iframe.yaml
alarm_control_panel: !include config/alarm_control_panel.yaml
calendar: !include config/calendar.yaml
prometheus: !include config/prometheus.yaml
switch: !include config/switch.yaml
utility_meter: !include config/utility_meter.yaml
group: !include_dir_merge_named groups/
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include_dir_merge_named scripts/
