all_doors:
  name: "Ovet"
  icon: mdi:door-closed
  entities:
    - binary_sensor.etuovi_door_window_2
    - binary_sensor.parvekkeen_ovi_door_window
all_windows:
  name: "Ikkunat"
  icon: mdi:window-closed
  entities:
    - binary_sensor.living_room_window_sensor_state_door_window
all_motion:
  name: "Liike"
  icon: mdi:walk
  entities:
    - binary_sensor.eteisen_liike
    - binary_sensor.keittion_liike
    - binary_sensor.pesuhuoneen_liike
all_kitchen_motion:
  name: "Keittiön liiketunnistimet"
  icon: mdi:walk
  entities:
    - binary_sensor.keittion_liike
all_hallway_motion:
  name: "Eteisen liiketunnistimet"
  icon: mdi:walk
  entities:
    - binary_sensor.eteisen_liike
all_toilet_motion:
  name: "Pesuhuoneen liiketunnistimet"
  icon: mdi:walk
  entities:
    - binary_sensor.pesuhuoneen_liike
