panic_alarm:
  name: "PANIIKKIHÄLYTYS!"
  done_message: "Paniikkihälytys on kuitattu."
  entity_id: input_boolean.panic_alarm_raised
  state: "on"
  repeat:
    - 1
    - 1
    - 8
    - 15
    - 15
    - 15
    - 60
  can_acknowledge: True
  skip_first: False
  notifiers:
    - mobile_app_iphone_markus
    - mobile_app_iphone_12_veera

fire_alarm:
  name: "PALOHÄLYTYS!"
  done_message: "Palohälytys on kuitattu."
  entity_id: input_boolean.fire_alarm_raised
  state: "on"
  repeat:
    - 1
    - 1
    - 8
    - 15
    - 15
    - 15
    - 60
  can_acknowledge: True
  skip_first: False
  notifiers:
    - mobile_app_iphone_markus
    - mobile_app_iphone_12_veera

burglar_alarm:
  name: "MURTOHÄLYTYS!"
  done_message: "Murtohälytys on kuitattu."
  entity_id: alarm_control_panel.ha_alarm
  state: "triggered"
  repeat:
    - 1
    - 1
    - 8
    - 15
    - 15
    - 15
    - 60
  can_acknowledge: True
  skip_first: False
  notifiers:
    - mobile_app_iphone_markus
    - mobile_app_iphone_12_veera
