home_mode:
  name: "Kodin tila"
  options:
    - "Awake"
    - "Asleep"
    - "Away"
    - "Emergency"
  initial: "Awake"
  icon: mdi:home-circle


# Hallway lights

light_base_mode_hallway:
  name: "Käytävän valoautomatiikka"
  options:
    - "Off"
    - "Manual"
    - "Automatic"
  initial: "Automatic"
  icon: mdi:lightbulb-auto


# Toilet lights

light_base_mode_toilet:
  name: "WC:n valoautomatiikka"
  options:
    - "Off"
    - "Manual"
    - "Automatic"
  initial: "Automatic"
  icon: mdi:lightbulb-auto


# Kitchen lights

light_base_mode_kitchen:
  name: "Keittiön valoautomatiikka"
  options:
    - "Off"
    - "Manual"
    - "Automatic"
  initial: "Automatic"
  icon: mdi:lightbulb-auto

