# Hallway lights

light_auto_lux_limit_hallway:
  name: "Käytävän valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Kitchen lights

light_auto_lux_limit_kitchen:
  name: "Keittiön valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Toilet lights

light_auto_lux_limit_toilet:
  name: "WC:n valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

# Others

default_notification_volume_sonos:
  min: 0
  max: 1
  step: 0.05
  mode: box
  name: "Sonosten ilmoitusten äänenvoimakkuus"
bedroom_humidifier_start_point:
  name: "MH kostutuksen käynnistys"
  min: 10
  max: 40
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
bedroom_humidifier_stop_point:
  name: "MH kostutuksen sammutus"
  min: 20
  max: 50
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
electricity_meter_reading:
  min: 0
  max: 9999.9
  step: 0.1
  mode: box
  unit_of_measurement: kWh
