living_room_brightness_target:
  name: "OH valaistuksen tavoite"
  min: 1
  max: 100
  step: 1
  icon: mdi:speedometer-medium
  mode: box
  unit_of_measurement: "%"
living_room_brightness_damping:
  name: "OH valaistuksen vaimennus"
  min: 0.1
  max: 10
  step: 0.1
  icon: mdi:speedometer-medium
  mode: box
kitchen_light_default_brightness:
  name: "Keittiön valaistuksen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
hallway_light_default_brightness:
  name: "Eteisen valaistuksen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
toilet_light_default_brightness:
  name: "Pesuhuoneen valaistuksen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
living_room_light_default_brightness:
  name: "Olohuoneen valaistuksen oletuskirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
living_room_light_auto_brightness:
  name: "Olohuoneen valaistuksen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
bedroom_light_default_brightness:
  name: "Makuuhuoneen valaistuksen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
decorative_lights_default_brightness:
  name: "Koristevalojen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
living_room_lightstrips_default_brightness:
  name: "Valonauhojen kirkkaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
kitchen_light_default_kelvin:
  name: "Keittiön valaistuksen värilämpötila"
  min: 2700
  max: 6500
  step: 1
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
hallway_light_default_kelvin:
  name: "Eteisen valaistuksen värilämpötila"
  min: 2700
  max: 6500
  step: 1
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
toilet_light_default_kelvin:
  name: "Pesuhuoneen valaistuksen värilämpötila"
  min: 2700
  max: 6500
  step: 1
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
living_room_light_default_kelvin:
  name: "Olohuoneen valaistuksen värilämpötila"
  min: 2700
  max: 6500
  step: 1
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
bedroom_light_default_kelvin:
  name: "Makuuhuoneen valaistuksen värilämpötila"
  min: 2700
  max: 6500
  step: 1
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
kitchen_light_turnoff_time:
  name: "Keittiön valaistuksen sammutusviive"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"
hallway_light_turnoff_time:
  name: "Eteisen valaistuksen sammutusviive"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"
toilet_light_turnoff_time:
  name: "Pesuhuoneen valaistuksen sammutusviive"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"
default_notification_volume_sonos:
  min: 0
  max: 1
  step: 0.05
  mode: box
  name: "Sonosten ilmoitusten äänenvoimakkuus"
bedroom_humidifier_start_point:
  name: "MH kostutuksen käynnistys"
  min: 20
  max: 40
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
bedroom_humidifier_stop_point:
  name: "MH kostutuksen sammutus"
  min: 30
  max: 60
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
