
# Living room lights

light_auto_awake_brightness_living_room:
  name: "OH valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_living_room:
  name: "OH valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_living_room:
  name: "OH valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_living_room:
  name: "OH valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_living_room:
  name: "OH valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_living_room:
  name: "OH valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_living_room:
  name: "OH valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_living_room:
  name: "OH valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_living_room:
  name: "OH valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_living_room:
  name: "OH valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_living_room:
  name: "OH valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_living_room:
  name: "OH valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_living_room:
  name: "OH valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_living_room:
  name: "OH valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_living_room:
  name: "OH valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Living room indirect lights

light_auto_awake_brightness_lr_indirect:
  name: "OH epäsuoran valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_lr_indirect:
  name: "OH epäsuoran valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_lr_indirect:
  name: "OH epäsuoran valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_lr_indirect:
  name: "OH epäsuoran valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_lr_indirect:
  name: "OH epäsuoran valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_lr_indirect:
  name: "OH epäsuoran valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_lr_indirect:
  name: "OH epäsuoran valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_lr_indirect:
  name: "OH epäsuoran valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_lr_indirect:
  name: "OH epäsuoran valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_lr_indirect:
  name: "OH epäsuoran valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_lr_indirect:
  name: "OH epäsuoran valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_lr_indirect:
  name: "OH epäsuoran valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_lr_indirect:
  name: "OH epäsuoran valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_lr_indirect:
  name: "OH epäsuoran valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_lr_indirect:
  name: "OH epäsuoran valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Hallway lights

light_auto_lux_limit_hallway:
  name: "Käytävän valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_brightness_hallway:
  name: "Käytävän valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_hallway:
  name: "Käytävän valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_hallway:
  name: "Käytävän valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_hallway:
  name: "Käytävän valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_hallway:
  name: "Käytävän valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_hallway:
  name: "Käytävän valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_hallway:
  name: "Käytävän valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_hallway:
  name: "Käytävän valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_hallway:
  name: "Käytävän valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_hallway:
  name: "Käytävän valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_hallway:
  name: "Käytävän valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Kitchen lights

light_auto_lux_limit_kitchen:
  name: "Keittiön valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_brightness_kitchen:
  name: "Keittiön valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_kitchen:
  name: "Keittiön valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_kitchen:
  name: "Keittiön valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_kitchen:
  name: "Keittiön valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_kitchen:
  name: "Keittiön valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_kitchen:
  name: "Keittiön valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_kitchen:
  name: "Keittiön valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_kitchen:
  name: "Keittiön valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_kitchen:
  name: "Keittiön valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_kitchen:
  name: "Keittiön valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_kitchen:
  name: "Keittiön valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Toilet lights

light_auto_lux_limit_toilet:
  name: "WC:n valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_brightness_toilet:
  name: "WC:n valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_toilet:
  name: "WC:n valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_toilet:
  name: "WC:n valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_toilet:
  name: "WC:n valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_toilet:
  name: "WC:n valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_toilet:
  name: "WC:n valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_toilet:
  name: "WC:n valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_toilet:
  name: "WC:n valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_toilet:
  name: "WC:n valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_toilet:
  name: "WC:n valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_toilet:
  name: "WC:n valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"


# Bedroom lights

light_auto_lux_limit_bedroom:
  name: "Makuuhuoneen valojen sytytysraja"
  min: 0
  max: 1000
  step: 1
  icon: mdi:brightness-7
  mode: box
  unit_of_measurement: "lx"

light_auto_awake_brightness_bedroom:
  name: "Makuuhuoneen valaistuksen kirkkaus AWAKE-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_awake_kelvin_bedroom:
  name: "Makuuhuoneen valaistuksen värilämpötila AWAKE-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_awake_turnoff_time_bedroom:
  name: "Makuuhuoneen valaistuksen sammutusviive AWAKE-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_away_brightness_bedroom:
  name: "Makuuhuoneen valaistuksen kirkkaus AWAY-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_away_kelvin_bedroom:
  name: "Makuuhuoneen valaistuksen värilämpötila AWAY-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_away_turnoff_time_bedroom:
  name: "Makuuhuoneen valaistuksen sammutusviive AWAY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_asleep_brightness_bedroom:
  name: "Makuuhuoneen valaistuksen kirkkaus ASLEEP-tilassa"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_auto_asleep_kelvin_bedroom:
  name: "Makuuhuoneen valaistuksen värilämpötila ASLEEP-tilassa"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_asleep_turnoff_time_bedroom:
  name: "Makuuhuoneen valaistuksen sammutusviive ASLEEP-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_auto_emergency_brightness_bedroom:
  name: "Makuuhuoneen valaistuksen kirkkaus EMERGENCY-tilassa"
  min: 1
  max: 255
  step: 1
  initial: 255
  icon: mdi:brightness-auto
  mode: box
light_auto_emergency_kelvin_bedroom:
  name: "Makuuhuoneen valaistuksen värilämpötila EMERGENCY-tilassa"
  min: 2700
  max: 6500
  step: 100
  initial: 4000
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_auto_emergency_turnoff_time_bedroom:
  name: "Makuuhuoneen valaistuksen sammutusviive EMERGENCY-tilassa"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"

light_result_brightness_bedroom:
  name: "Makuuhuoneen valaistuksen kirkkauden ohjaus"
  min: 1
  max: 255
  step: 1
  icon: mdi:brightness-auto
  mode: box
light_result_kelvin_bedroom:
  name: "Makuuhuoneen valaistuksen lämpötilan ohjaus"
  min: 2700
  max: 6500
  step: 100
  icon: mdi:temperature-kelvin
  unit_of_measurement: "K"
  mode: box
light_result_turnoff_time_bedroom:
  name: "Makuuhuoneen valaistuksen sammutusviiveen ohjaus"
  min: 1
  max: 60
  icon: mdi:timer-sand
  unit_of_measurement: "m"




# Others

default_notification_volume_sonos:
  min: 0
  max: 1
  step: 0.05
  mode: box
  name: "Sonosten ilmoitusten äänenvoimakkuus"
bedroom_humidifier_start_point:
  name: "MH kostutuksen käynnistys"
  min: 20
  max: 40
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
bedroom_humidifier_stop_point:
  name: "MH kostutuksen sammutus"
  min: 30
  max: 60
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
electricity_meter_reading:
  min: 0
  max: 9999.9
  step: 0.1
  mode: box
  unit_of_measurement: kWh

scfb_ch1_kp:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH1 KP"
scfb_ch1_ki:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH1 KI"
scfb_ch1_kd:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH1 KD"
scfb_ch1_target:
  min: 10.0
  max: 40.0
  step: 0.1
  mode: box
  name: "SCFB CH1 Target"
scfb_ch2_kp:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH2 KP"
scfb_ch2_ki:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH2 KI"
scfb_ch2_kd:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "SCFB CH2 KD"
scfb_ch2_target:
  min: 10.0
  max: 40.0
  step: 0.1
  mode: box
  name: "SCFB CH2 Target"

fcb_test_ch1_kp:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH1 KP"
fcb_test_ch1_ki:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH1 KI"
fcb_test_ch1_kd:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH1 KD"
fcb_test_ch1_target:
  min: 10.0
  max: 40.0
  step: 0.1
  mode: box
  name: "FCB Test CH1 Target"
fcb_test_ch2_kp:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH2 KP"
fcb_test_ch2_ki:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH2 KI"
fcb_test_ch2_kd:
  min: 0.0
  max: 100.0
  step: 0.1
  mode: box
  name: "FCB Test CH2 KD"
fcb_test_ch2_target:
  min: 10.0
  max: 40.0
  step: 0.1
  mode: box
  name: "FCB Test CH2 Target"
