default_notification_volume_sonos:
  min: 0
  max: 1
  step: 0.05
  mode: box
  name: "Sonosten ilmoitusten äänenvoimakkuus"
bedroom_humidifier_start_point:
  name: "MH kostutuksen käynnistys"
  min: 10
  max: 40
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
bedroom_humidifier_stop_point:
  name: "MH kostutuksen sammutus"
  min: 20
  max: 50
  step: 1
  icon: mdi:water-percent
  unit_of_measurement: "%"
electricity_meter_reading:
  min: 0
  max: 9999.9
  step: 0.1
  mode: box
  unit_of_measurement: kWh
