home_mode:
  name: "Kodin tila"
  options:
    - "Awake"
    - "Asleep"
    - "Away"
    - "Emergency"
  initial: "Awake"
  icon: mdi:home-circle


# Living room lights

light_base_mode_living_room:
  name: "OH valoautomatiikka"
  options:
    - "Off"
    - "Manual"
    - "Automatic"
  initial: "Automatic"
  icon: mdi:lightbulb-auto

light_auto_home_mode_living_room:
  name: "OH valojen automatiikan toimintatila"
  options:
    - "Awake"
    - "Asleep"
    - "Away"
    - "Emergency"
  initial: "Awake"
  icon: mdi:lightbulb-auto


# Hallway lights

light_base_mode_hallway:
  name: "Käytävän valoautomatiikka"
  options:
    - "Off"
    - "Manual"
    - "Automatic"
  initial: "Automatic"
  icon: mdi:lightbulb-auto

light_auto_home_mode_hallway:
  name: "Käytävän valojen automatiikan toimintatila"
  options:
    - "Awake"
    - "Asleep"
    - "Away"
    - "Emergency"
  initial: "Awake"
  icon: mdi:lightbulb-auto
