switch:
  name: "Office UPS Plug Switch"
  unique_id: "office-ups-power-plug"
  command_topic: "shellies/shellyplug-s-C111E6/relay/0/command"
  state_topic: "shellies/shellyplug-s-C111E6/relay/0"
  payload_off: "off"
  payload_on: "on"

binary_sensor:
  name: "MH äänihälytin"
  state_topic: "sensor/alarmlight_1/Sound/Enabled"
  payload_on: "1"
  payload_off: "0"
  device_class: "sound"

sensor:
  name: "Pesuhuoneen lämpötila"
  state_topic: "sensor/bathroom/env/temp"
  unit_of_measurement: "°C"
  state_class: measurement
sensor:
  name: "Pesuhuoneen ESP:n paristo"
  state_topic: "sensor/bathroom/Battery/Battery"
  unit_of_measurement: "%"
sensor:
  name: "Makuuhuoneen lämpötila"
  state_topic: "sensor/alarmlight_1/env/Temperature"
  unit_of_measurement: "°C"
  state_class: measurement
sensor:
  name: "Makuuhuoneen kosteus"
  state_topic: "sensor/alarmlight_1/env/Humidity"
  unit_of_measurement: "%"
  state_class: measurement
sensor:
  name: "Makuuhuoneen paine"
  state_topic: "sensor/alarmlight_1/env/Pressure"
  value_template: "{{ (value | float) + 5.0 }}"
  unit_of_measurement: "hPa"
  state_class: measurement
sensor:
  name: "Palopainikkeen pariston lataus"
  state_topic: "sensor/fire-alarm-button-1/Battery/Volts"
  value_template: "{{ ((value | float) * 100) - 200 }}"
  unit_of_measurement: "%"
sensor:
  name: "SCFB Temp"
  state_topic: "home/server/cabinet/exhausttemp"
  unit_of_measurement: "°C"
  state_class: measurement
sensor:
  name: "SCFB Setpoint"
  state_topic: "home/server/cabinet/setpoint"
  unit_of_measurement: "°C"
  state_class: measurement
sensor:
  name: "SCFB Fan"
  state_topic: "home/server/cabinet/fanspeed"
  unit_of_measurement: "rpm"
  state_class: measurement
sensor:
  name: "SCFB PID"
  state_topic: "home/server/cabinet/pwmout"
  value_template: "{{ ( 100 - ( (value | float) / 230 * 100 ) ) | round(1) }}"
  unit_of_measurement: "%"
  state_class: measurement
sensor:
  name: "Event topic"
  state_topic: "notify/cmd"
sensor:
  name: "Office UPS Plug Power"
  unique_id: "office-ups-power-plug-power"
  state_topic: "shellies/shellyplug-s-C111E6/relay/0/power"
  unit_of_measurement: "W"
  force_update: "true"
  device_class: "power"
  state_class: measurement
sensor:
  name: "Office UPS Plug Temp"
  unique_id: "office-ups-power-plug-temp"
  state_topic: "shellies/shellyplug-s-C111E6/temperature"
  unit_of_measurement: "°C"
  force_update: "true"