switch:
  - name: "Shellyplug S C111E6 Switch"
    unique_id: "shellyplug-s-c111e6-switch"
    command_topic: "shellies/shellyplug-s-C111E6/relay/0/command"
    state_topic: "shellies/shellyplug-s-C111E6/relay/0"
    payload_off: "off"
    payload_on: "on"

binary_sensor:
  - name: "MH äänihälytin"
    state_topic: "sensor/alarmlight_1/Sound/Enabled"
    payload_on: "1"
    payload_off: "0"
    device_class: "sound"

sensor:
  - name: "Pesuhuoneen lämpötila"
    state_topic: "sensor/bathroom/env/temp"
    unit_of_measurement: "°C"
    state_class: measurement
    
  - name: "Pesuhuoneen ESP:n paristo"
    state_topic: "sensor/bathroom/Battery/Battery"
    unit_of_measurement: "%"

  - name: "Makuuhuoneen lämpötila"
    state_topic: "sensor/alarmlight_1/env/Temperature"
    unit_of_measurement: "°C"
    state_class: measurement

  - name: "Makuuhuoneen kosteus"
    state_topic: "sensor/alarmlight_1/env/Humidity"
    unit_of_measurement: "%"
    state_class: measurement

  - name: "Makuuhuoneen paine"
    state_topic: "sensor/alarmlight_1/env/Pressure"
    value_template: "{{ (value | float) + 5.0 }}"
    unit_of_measurement: "hPa"
    state_class: measurement

  - name: "Palopainikkeen pariston lataus"
    state_topic: "sensor/fire-alarm-button-1/Battery/Volts"
    value_template: "{{ ((value | float) * 100) - 200 }}"
    unit_of_measurement: "%"

  - name: "Event topic"
    state_topic: "notify/cmd"

  - name: "Shellyplug S C111E6 Power"
    unique_id: "shellyplug-s-c111e6-power"
    state_topic: "shellies/shellyplug-s-C111E6/relay/0/power"
    unit_of_measurement: "W"
    force_update: "true"
    device_class: "power"
    state_class: measurement

  - name: "Shellyplug S C111E6 Temp"
    unique_id: "shellyplug-s-c111e6-temp"
    state_topic: "shellies/shellyplug-s-C111E6/temperature"
    unit_of_measurement: "°C"
    force_update: "true"
