- name: syslog_info
  platform: syslog
  facility: local0

- name: syslog_emergency
  platform: syslog
  facility: local0
  priority: 5

- name: syslog_critical
  platform: syslog
  facility: local0
  priority: 3
