- name: ALL_DEVICES
  platform: group
  services:
    - service: mobile_app_ipad
    - service: mobile_app_ipad_markus
    - service: mobile_app_iphone_12_veera
    - service: mobile_app_iphone_markus

- name: main_mobile_phones
  platform: group
  services:
    - service: mobile_app_iphone_12_veera
    - service: mobile_app_iphone_markus

- name: syslog_info
  platform: syslog
  facility: local0

- name: syslog_emergency
  platform: syslog
  facility: local0
  priority: 5

- name: syslog_critical
  platform: syslog
  facility: local0
  priority: 3
