- platform: template
  sensors:
    wan_router_ping_round_time:
      value_template: "{{ state_attr('binary_sensor.ping_wan_router', 'round_trip_time_avg') | float(0.0) }}"
      unit_of_measurement: "ms"
    google_ping_round_time:
      value_template: "{{ state_attr('binary_sensor.ping_google', 'round_trip_time_avg') | float(0.0) }}"
      unit_of_measurement: "ms"
    living_room_ap_ping_round_time:
      value_template: "{{ state_attr('binary_sensor.ping_living_room_ap', 'round_trip_time_avg') | float(0.0) }}"
      unit_of_measurement: "ms"
    sun_elevation:
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      friendly_name: "Auringon korkeus"
      unit_of_measurement: "°"
    sun_azimuth:
      value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
      friendly_name: "Auringon sijainti"
      unit_of_measurement: "°"
    bedroom_humidifier_status:
      friendly_name: "MH ilmankostuttimen tila"
      value_template: >-
        {% if is_state('input_boolean.bedroom_humidifier_empty', 'on') %}
          empty
        {% elif is_state('switch.tp_link_smart_plug_5f83', 'off') %}
          off
        {% elif (states('sensor.tp_link_smart_plug_5f83_current_consumption') | float(0.0)) > 50 %}
          humidifying
        {% elif is_state('switch.tp_link_smart_plug_5f83', 'on') %}
          standby
        {% else %}
          failed
        {% endif %}
- platform: time_date
  display_options:
    - "time"
    - "date"
