yearly_energy:
  source: sensor.energy_reading
  name: Vuosittainen energian kulutus
  cycle: yearly
monthly_energy:
  source: sensor.energy_reading
  name: Kuukausittainen energian kulutus
  cycle: monthly
weekly_energy:
  source: sensor.energy_reading
  name: Viikoittainen energian kulutus
  cycle: weekly