- name: "Home"
  latitude: !secret ha_latitude
  longitude: !secret ha_longlitude
  radius: 100
  icon: mdi:home
- name: "P-R"
  latitude: !secret pr_lat
  longitude: !secret pr_lon
  radius: 150
  icon: mdi:test-tube
