- id: emergency_mode_start_automations
  alias: "Starting Emergency mode"
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: "Emergency"
  action:
    - service: script.turn_off_all_appliances
    - service: input_select.select_option
      target:
        entity_id: input_select.light_base_mode_living_room
      data:
        option: "Automatic"

# - id: stop_emerg_mode_automations
#   alias: "Stopping emergency mode"
#   trigger:
#     - platform: state
#       entity_id: input_select.home_mode
#       from: "Emergency"
#   action:
#     - service: light.turn_off
#       target:
#         entity_id: light.yopoydat

- id: automated_disarm_on_awake
  alias: "Automaattinen disarm kun siirrytään awake-tilaan"
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: "Awake"
      from: "Asleep"
  action:
    - service: mqtt.publish
      data:
        topic: "notify/burglar_alarm_state_request"
        payload: "DISARM"
        qos: 1
        retain: 0

- id: automated_arm_night
  alias: "Automated arm night"
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: "Asleep"
  action:
    - service: mqtt.publish
      data:
        topic: "notify/burglar_alarm_state_request"
        payload: "ARM_NIGHT"
        qos: 1
        retain: 0

- id: armed_away_activation_test
  alias: "Poissa-valvonnan aktivointitesti"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: "armed_away"
      for:
        seconds: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.etuovi_door_window_2
        state: "on"
  action:
    - service: notify.main_mobile_phones
      data:
        message: "Asunto ei ole suojattu, joten murtohälytintä ei voitu aktivoida. Tarkista asunto ja yritä uudelleen."
    - service: mqtt.publish
      data:
        topic: "notify/burglar_alarm_state_request"
        payload: "DISARM"
        qos: 1
        retain: 0
    - service: notify.syslog_info
      data:
        message: "Asunto ei ole suojattu, joten murtohälytintä ei voitu aktivoida."

- id: motion_notification
  alias: "Liikeilmoitus"
  trigger:
    - platform: state
      entity_id: group.all_motion
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.motion_notify
      state: "on"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.motion_notify
    - service: notify.main_mobile_phones
      data:
        message: "Liikettä havaittu!"
    - service: notify.syslog_info
      data:
        message: "Liikeilmoitus."

- id: alarm_trigger_while_home_day_automation
  alias: "Armed home -tilan hälytyksen aktivointilogiikka"
  trigger:
    - platform: state
      entity_id: binary_sensor.etuovi_door_window_2
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: "armed_home"
  action:
    - service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.ha_alarm

- id: alarm_trigger_while_home_night_automation
  alias: "Armed night -tilan hälytyksen aktivointilogiikka"
  trigger:
    - platform: state
      entity_id: binary_sensor.etuovi_door_window_2
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: "armed_night"
  action:
    - service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.ha_alarm

- id: alarm_trigger_while_away_automation
  alias: "Armed away -tilan hälytyksen aktivointilogiikka"
  trigger:
    - platform: state
      entity_id: binary_sensor.etuovi_door_window_2
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: "armed_away"
  action:
    - service: alarm_control_panel.alarm_trigger
      target:
        entity_id: alarm_control_panel.ha_alarm

- id: alarm_triggered_automation
  alias: "Tee murtohälytys"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: "triggered"
    - platform: state
      entity_id: sensor.alarm_command_topic
      to: "event,burglar"
  condition:
    - condition: state
      entity_id: input_boolean.burglar_alarm_raised
      state: "off"
  action:
    - service: script.raise_alarm
      data:
        command_payload: "event,burglar"
        alarm_boolean: input_boolean.burglar_alarm_raised
        alarm_title: "Murtohälytys!"
        alarm_message: "Murtohälytys lähetetty."

- id: fire_alarm_automation
  alias: "Tee palohälytys"
  trigger:
    - platform: mqtt
      topic: "notify/cmd"
      payload: "event,fire"
    - platform: state
      entity_id: binary_sensor.server_cabinet_fire_alarm
      to: "on"
    - platform: state
      entity_id: binary_sensor.server_room_smoke_detector_smoke_detected
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.fire_alarm_raised
      state: "off"
  action:
    - service: script.raise_alarm
      data:
        command_payload: "event,fire"
        alarm_boolean: input_boolean.fire_alarm_raised
        alarm_title: "Palohälytys!"
        alarm_message: "Kodin palovaroitin hälyttää!"

- id: panic_button_automation
  alias: "Tee paniikkihälytys"
  trigger:
    - platform: mqtt
      topic: "notify/cmd"
      payload: "event,panic"
  condition:
    - condition: state
      entity_id: input_boolean.panic_alarm_raised
      state: "off"
  action:
    - service: script.raise_alarm
      data:
        command_payload: "event,panic"
        alarm_boolean: input_boolean.panic_alarm_raised
        alarm_title: "Paniikkihälytys!"
        alarm_message: "Paniikkihälytys lähetetty."

- id: clear_alarms
  alias: "Hälytysten kuittaus"
  trigger:
    - platform: mqtt
      topic: "notify/cmd"
      payload: "event,clear"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.burglar_alarm_raised
        state: "on"
      - condition: state
        entity_id: input_boolean.fire_alarm_raised
        state: "on"
      - condition: state
        entity_id: input_boolean.panic_alarm_raised
        state: "on"
  action:
    - service: script.turn_on
      target:
        entity_id: script.reverse_emergency_state

- id: leaving_home_automation
  alias: "Kotoa poistumisautomaatiot"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: "armed_away"
      for:
        seconds: 10
  condition:
    - condition: state
      entity_id: group.master_warning
      state: "off"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.home_mode
      data:
        option: "Away"

- id: returning_home_automation
  alias: "Kotiin palaamisen automaatiot"
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: "disarmed"
      from: "pending"
  condition:
    - condition: state
      entity_id: group.master_warning
      state: "off"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.home_mode
      data:
        option: "Awake"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.motion_notify

- id: perimeter_notifications
  alias: "Kuori-ilmoitukset"
  trigger:
    - platform: state
      entity_id: binary_sensor.etuovi_door_window_2
      to: "on"
    - platform: state
      entity_id: binary_sensor.parvekkeen_ovi_sensor_state_door_window_2
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.perimeter_notifications
      state: "on"
  action:
    - service: notify.main_mobile_phones
      data:
        message: "{{ trigger.to_state.name }} on avattu"
    - service: notify.syslog_info
      data:
        message: "{{ trigger.to_state.name }} on avattu"
    - service: mqtt.publish
      data:
        topic: "notify/cmd"
        payload: "event,doorbell"
        qos: 1
        retain: 0

- id: activate_master_caution
  alias: "Activate Master Caution"
  trigger:
    - platform: state
      entity_id: group.master_caution
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.master_caution_triggered
      state: "off"
  action:
    - service: mqtt.publish
      data:
        topic: "notify/cmd"
        payload: "event,master_caution"
        qos: 1
        retain: 0
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.master_caution_triggered
    - service: notify.syslog_critical
      data:
        message: "Master Caution!"

- id: clear_master_caution_on_ack
  alias: "Clears Master Caution on ack if group is safe"
  trigger:
    - platform: state
      entity_id: input_boolean.ack_master_caution
      to: "on"
  condition:
    - condition: state
      entity_id: group.master_caution
      state: "off"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_caution_triggered
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.ack_master_caution

- id: clear_master_caution_if_acked_and_group_safe
  alias: "Clears Master Caution if acked and group goes safe"
  trigger:
    - platform: state
      entity_id: group.master_caution
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.ack_master_caution
      state: "on"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.master_caution_triggered
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.ack_master_caution

- id: burglar_alarm_tag_scan
  alias: "Toggles burglar alarm between away-disarmed on tag scan"
  mode: single
  max_exceeded: silent
  variables:
    tags:
      - 0402e39c-2f9f-4540-9f9d-78bb2b143a64
  trigger:
    - platform: event
      event_type: tag_scanned
  condition:
    - "{{ trigger.event.data.tag_id in tags }}"
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.ha_alarm
              state: disarmed
          sequence:
            - service: mqtt.publish
              data:
                topic: "notify/burglar_alarm_state_request"
                payload: "ARM_AWAY"
                qos: 1
                retain: 0
        - conditions:
            - condition: state
              entity_id: alarm_control_panel.ha_alarm
              state:
                - armed_away
                - armed_night
                - armed_home
                - pending
                - triggered
          sequence:
            - service: mqtt.publish
              data:
                topic: "notify/burglar_alarm_state_request"
                payload: "DISARM"
                qos: 1
                retain: 0
    - delay: 2
